### ISSUE TITLE
Release building

### ISSUE THREAD

**Issue by crc-32** [pebble-dev/mobile-app#10]
Currently a release build fails with the following:
```
/home/crc32/Documents/fossil/build/app/tmp/kapt3/stubs/release/io/rebble/fossil/di/AppComponent.java:8: error: [Dagger/DependencyCycle] Found a dependency cycle:
public abstract interface AppComponent {
                ^
      error.NonExistentClass is injected at
          io.rebble.fossil.di.LibPebbleModule.provideBlobDbService(protocolHandler)
      error.NonExistentClass is requested at
          io.rebble.fossil.di.AppComponent.createProtocolHandler()
```

**Comment by matejdro** [comment]
From what I see, issue lies with `libpebble`. In debug mode, we use `libpebblecommon-android-debug` artifact which is normal, but on release mode we use `libpebblecommon-android` which appears to be completely empty:

![image](https://user-images.githubusercontent.com/507922/94682350-1a9b7100-0325-11eb-807b-46e8bf2ec06e.png)

**Comment by AliceGrey** [comment]
This is a blocker for uploading to Play Store for internal alpha testing.

**Comment by AliceGrey** [comment]
@crc-32 & @matejdro  I can confirm this was fixed by https://github.com/pebble-dev/mobile-app/commit/339a4ae47388ab9e5899a3324439098cbb0eaafc and https://github.com/pebble-dev/mobile-app/commit/74a3a93c157d8e7edd02b2aa2475bc88a8d77010

**Comment by matejdro** [comment]
Awesome
