### ISSUE TITLE
Connecting watch is not at the top

### ISSUE THREAD

**Issue by matejdro** [pebble-dev/mobile-app#102]
When watch is "Connecting", background services are running, so top part should not say background service stopped. Maybe connecting watch should even move to the top?  Additionally, When watch is "Connecting", there is no way to stop this connection

![image](https://user-images.githubusercontent.com/507922/109381771-900f6b80-78dc-11eb-8138-c4a941ac7f37.png)

**Comment by AliceGrey** [comment]
This is how it is currently represented in the figma design. @piggehperson do you have any ideas on how to re-design this portion of the UI given @matejdro's feedback?

**Comment by piggehperson** [comment]
@AliceGrey I dont actually have this in the figma but i think that is how it should behave. Connecting watches should move to the top of the list

**Comment by AliceGrey** [comment]
> @AliceGrey I dont actually have this in the figma but i think that is how it should behave. Connecting watches should move to the top of the list

Sorry that was mostly meant for "When watch is "Connecting", background services are running, so top part should not say background service stopped."

**Comment by piggehperson** [comment]
When nothing is trying to connect, the message should show at the top. When a watch is connected or trying to connect, that watch should show at the top of the list

**Comment by piggehperson** [comment]
![image](https://user-images.githubusercontent.com/22055104/109438922-22f1f800-79fa-11eb-9306-0a55b65eb3e9.png)

**Comment by AliceGrey** [comment]
> When nothing is trying to connect, the message should show at the top. When a watch is connected or trying to connect, that watch should show at the top of the list

I think @matejdro ' s concern with the top message was the wording of "background service stopped" as the background services are still running even if there is no watch connected.

**Comment by matejdro** [comment]
I think designs from https://github.com/pebble-dev/mobile-app/issues/102#issuecomment-787555621 fix the issue completely.
