### ISSUE TITLE
System statusbar icons are black on dark background

### ISSUE THREAD

**Issue by matejdro** [pebble-dev/mobile-app#119]
Challenge: tell me the time on this image:

![image](https://user-images.githubusercontent.com/507922/109966751-e4f21e00-7cf0-11eb-8713-58b4242756e7.png)

This is on Android 10

**Comment by piggehperson** [comment]
GODS thank you for bringing this up. Statusbar icons are inverted from the colors they should be. They should be black on light background, and white on dark background. Also, the status bar itself shouldn't have the dark background, it should be transparent
