### ISSUE TITLE
Scrolling through notification app list is laggy

### ISSUE THREAD

**Issue by matejdro** [pebble-dev/mobile-app#125]
You can clearly see dropped frames when scrolling through list of apps in notification settings ("Choose which apps can alert your watch" page). I don't know a lot about flutter, but there is probably a way to do something like RecyclerView to avoid jankiness?

This is on OnePlus 7 Pro, which is fairly high end device. Cheaper phones will have more issues.

This is pretty low priority (we have lots of bigger fish to fry first), so I'm creating new `polish` tag for issues like this.

**Comment by crc-32** [comment]
I have noticed this, also dropped frames are logged when initially opening the notifications settings page too

**Comment by matejdro** [comment]
Fixed by https://github.com/pebble-dev/mobile-app/pull/165
