### ISSUE TITLE
[Request] Submit Android App To F-Droid

### ISSUE THREAD

**Issue by seniorm0ment** [pebble-dev/mobile-app#146]
**Request:**
Requesting addition of the Android app to be submitted to F-Droid (when ready).

**Related Resources:**
https://f-droid.org/en/docs/Submitting_to_F-Droid_Quick_Start_Guide/
https://f-droid.org/en/docs/Inclusion_Policy/
https://f-droid.org/en/docs/Inclusion_How-To/

**Comment by lolrepeatlol** [comment]
FWIW, I know there has been some thought about using GMS for instant timeline pins so it's worth noting that if submitting to F-Droid, there'd likely have to be a backup system in place for not using GMS and getting timeline pins the old fashioned way (every 30 min/3 hrs). I can't think of anything else that would need GMS though

**Comment by seniorm0ment** [comment]
I personally would be heavily against using GMS.
That being said, if it is inevitable then a separate build without it like lots of apps do.

**Comment by piggehperson** [comment]
That's the plan! Rebble already has an app hosted on F-droid (https://f-droid.org/en/packages/io.rebble.charon/), and AFAIK we have always been planning to release this app there too. Like @lolrepeatlol said, we may have to drop features like GMS, but hopefully the user experience will be largely the same.

**Comment by lolrepeatlol** [comment]
> 
> 
> I personally would be heavily against using GMS.
> That being said, if it is inevitable then a separate build without it like lots of apps do.

GMS is required to be taken out when submitting to F-Droid, so if F-Droid happens, this will happen :)

**Comment by matejdro** [comment]
> I personally would be heavily against using GMS.

Unfortunately there is no alternative when it comes to instant push updates. Google applies heavy background restrictions to everything but their own push solution. We can do polling on the F-droid version but it is much less efficient and slower.
