### ISSUE TITLE
fitness quites tracking when disconnected

### ISSUE THREAD

**Issue by hartunic** [pebble-dev/mobile-app#177]
Fitness quites tracking when pebble smartwatch disconnects for cobble and watch don't reconnect when watch battery is 50% or less

**Comment by matejdro** [comment]
What fitness tracking? Cobble does not have Pebble health yet.

**Comment by hartunic** [comment]
Build in fitness on pebble smartwatches

**Comment by matejdro** [comment]
Yeah, this is not supported yet unfortunately. So any bug reports regarding that are pointless.
