### ISSUE TITLE
Grammatical error in wiki page

### ISSUE THREAD

**Issue by BlockArchitech** [pebble-dev/mobile-app#198]
In the "Android side" wiki page, under "Communicating with flutter" there is this sentence:

Android app uses a bunch of FlutterBridge classes to implement pigeon communication([see Flutter to Native for more on Pigeon](https://github.com/pebble-dev/mobile-app/wiki/Flutter-to-Native-communication).

However, sentence is missing a space between communication and the link, and there is no ending ) in text for the link.

The sentence should be changed to this:

Android app uses a bunch of FlutterBridge classes to implement pigeon communication ([see Flutter to Native for more on Pigeon](https://github.com/pebble-dev/mobile-app/wiki/Flutter-to-Native-communication)).

**Comment by crc-32** [comment]
Corrected, thanks!
