### ISSUE TITLE
State of iOS

### ISSUE THREAD

**Issue by q231950** [pebble-dev/mobile-app#203]
Hi,

I'm an iOS engineer who'd love to get my pebble up and running again.

I made the app run on an iOS device and looked into pairing when I noticed that most (if not all) iOS native bridges are not implemented at the moment - is that correct or am I missing something?

**Comment by NoahAndrews** [comment]
I haven't done anything with the iOS side personally, but I know there's an iOS branch that is further ahead with support for that platform.

**Comment by q231950** [comment]
Ok cool, I'll have a look. Thanks @NoahAndrews 🙂

**Comment by crc-32** [comment]
The iOS branch is mostly working although the last few changes there I believe may have broken it, but you should just be able to stub the missing method as it's android specific (I'm not always working on a mac which complicates things)

**Comment by q231950** [comment]
I am reopening this as I have created #204 to make the `ios` branch compile and run again. Hope this is ok with you guys @NoahAndrews @crc-32. 

One more question - are you generally looking for support regarding iOS @crc-32?

**Comment by crc-32** [comment]
Very much so, yes
