### ISSUE TITLE
Google fit sync

### ISSUE THREAD

**Issue by jellyedwards** [pebble-dev/mobile-app#208]
Steps or sleep never get synced to Google fit. "Sync with Google fit" is checked and I can see Pebble in the list of connected apps. I'm using Android version 10 & 4.42.

**Comment by matejdro** [comment]
This is not Cobble related, Cobble does not even support any Fit features yet.

**Comment by jellyedwards** [comment]
Sorry I'm not familiar with the repositories @matejdro where should this issue go?

**Comment by NoahAndrews** [comment]
I think the answer is that there's nothing we can do to fix this in the official Pebble app, and so you'll just have to wait for Cobble to be ready for daily use and have Fit support.
