### ISSUE TITLE
pebble mobile app cannot detect bluetooth devices on Android 13

### ISSUE THREAD

**Issue by batfood** [pebble-dev/mobile-app#209]
Pixel 6 w/Android 13 Build TP1A.220624.021
Pebble app v.4.4.2-1405-62d45d7d7-endframe
Pebble Time Steel w/Firmware v4.4.0-rbl

Workarounds tried:
Phone - Cleared App Storage + Cache Data, Deleted Bluetooth paired devices
Pebble - Deleted Bluetooth paired devices + Shutdown + Restart

Result: Since Android 13 update, Pebble app nolonger detects Pebble, even though Both LE and normal Pebble devices show up in available list.

**Comment by piggehperson** [comment]
This repository is for the early-in-development Rebble app to replace the Pebble Inc. app, it is not for the Pebble app itself. Try making sure your watch is unpaired from your phone's Bluetooth menu, then set your phone to airplane mode, turn on Bluetooth, and pair from the Pebble app.
