### ISSUE TITLE
Add Music Control

### ISSUE THREAD

**Issue by matejdro** [pebble-dev/mobile-app#25]
Depends on https://github.com/pebble-dev/mobile-app/issues/15

At the moment, there are two ways to do this on Android:

* The old Bluetooth Intent way (like original Pebble app) - This allows user to pick one app in the settings (or on the watch) and always control that app. Big pro of this method is that user can start playback even when app is not active. Con is that many modern music players (such as Youtube Music or Google Podcasts) do not support that anymore, so user cannot control those apps.

* New Notification Service way. This one is more modern and supports pretty much all media apps. Con of this is that it only controls last active app (user cannot switch between Podcasts and Spotify for example). Also this method has more information on playback (such as current position in track).

Which path should we take? I lean for for the second option.

**Comment by piggehperson** [comment]
Hm. I feel like I'm leaning towards notification service, as long as it can still handle things like the user switching media apps on the phone.

**Comment by matejdro** [comment]
I can add sort of hybrid approach I guess that would use notification service, but fall back to bluetooth intent to switch between apps. However, switching still wouldn't support many new apps.
