### ISSUE TITLE
Android Notifications

### ISSUE THREAD

**Issue by PeterKW** [pebble-dev/mobile-app#251]
Sorry if this is the wrong place for this. I'm not sure how to give the notification permission? Do i need adb?

**Comment by PeterKW** [comment]
![Screenshot_20240506-180421.png](https://github.com/pebble-dev/mobile-app/assets/13779157/4ca78d9f-079c-411b-affd-a72b082ea260)

**Comment by hellcp** [comment]
This repository is not about the existing Pebble app, but a new implementation of an app from the ground up. As such we can't help you here, you will have more luck asking for support in the rebble discord server
