### ISSUE TITLE
Easiest way to test

### ISSUE THREAD

**Issue by PeterKW** [pebble-dev/mobile-app#298]
https://github.com/pebble-dev/mobile-app/issues/251#issuecomment-2096710970

This sounds interesting

What is the easiest way to test this? Are there compiled versions on FDroid anywhere?

**Comment by jwise** [comment]
Please do not keep opening issues for the same thing.  The app is not in a state that is really ready for general testing by noninvolved users (i.e., by whoever finds it on FDroid).  If you would like to discuss this, or to help test the app, feel free to drop into the Rebble Discord server.  Thanks!

**Comment by PeterKW** [comment]
I wasn't aware there was a discord server. I'll see if I can find it
