### ISSUE TITLE
Master does not compile. Has ambiguous import

### ISSUE THREAD

**Issue by kenthinson** [pebble-dev/mobile-app#6]
Line 23
`onGenerateRoute: Router.generateRoute,`
showing error. 
`{
	"resource": "/Users/kent/Developer/mobile-app/lib/main.dart",
	"owner": "dart",
	"code": {
		"value": "ambiguous_import",
		"target": {
			"$mid": 1,
			"external": "https://dart.dev/tools/diagnostic-messages#ambiguous_import",
			"path": "/tools/diagnostic-messages",
			"scheme": "https",
			"authority": "dart.dev",
			"fragment": "ambiguous_import"
		}
	},
	"severity": 8,
	"message": "The name 'Router' is defined in the libraries 'package:flutter/src/widgets/router.dart' and 'package:fossil/ui/Router.dart'.\nTry using 'as prefix' for one of the import directives, or hiding the name from all but one of the imports.",
	"source": "dart",
	"startLineNumber": 23,
	"startColumn": 24,
	"endLineNumber": 23,
	"endColumn": 30,
	"tags": []
}`
![Screen Shot 2020-09-19 at 5 11 57 PM](https://user-images.githubusercontent.com/2245494/93690201-53248a80-fa9b-11ea-816e-0656e24f0a34.png)

**Comment by kenthinson** [comment]
I was able to get it to compile with this edit in main.dart however it's probably not the right fix long term.

`import 'package:fossil/ui/Router.dart' as R;`
`onGenerateRoute: R.Router.generateRoute,`

**Comment by matejdro** [comment]
Is it possible that your Flutter installation somehow contains two of those classes? Can you try removing dart / flutter SDK completely and reinstalling?

**Comment by AliceGrey** [comment]
@matejdro This was resolved by @crc-32's BLE Merge

**Comment by crc-32** [comment]
Solved
