### ISSUE TITLE
Watch data(firmware v, model, color, etc) needs to be stored after first connection to watch

### ISSUE THREAD

**Issue by AliceGrey** [pebble-dev/mobile-app#72]
Watch data needs to be stored after first connection to watch so it can be accessed in the My Watches page.

**Comment by DreadBoy** [comment]
Can I take a stab at this task? Is anybody working on it?

**Comment by AliceGrey** [comment]
@DreadBoy Once the pair page is converted to a Hook widget this will be really simple. Currently in my PR for the watches page there is the beginning of an implementation in the watches tab but it requires the page to be a hookwidget to access the data needed.

**Comment by AliceGrey** [comment]
Look around line 34 of watches_tab.dart in my PR for the current hack that the fix for this issue will replace.
