### ISSUE TITLE
UI: Settings

### ISSUE THREAD

**Issue by DreadBoy** [pebble-dev/mobile-app#82]
Prerequisite components
- [x] Cupertino navigation #84 
- [x] Material theming and components #90 
  - [x] button
  - [x] FAB button
  - [x] card (with support for theming)
  - [x] bottom sheet
  - [x] modal dialog (with support for theming)

Settings screen #90
- [x] Rebble account card
- [x] Custom list tiles
Notifications screen  #90
- [x] Custom list tiles, some are reusable, some are specific to this screen
Alerting apps screen  #90
- [ ] We need native plugin to support [NotificationListener](https://developer.android.com/reference/android/service/notification/NotificationListenerService), work on that is tracked in #94
- [x] Inline bottom sheet (it's different than modal bottom sheet)
- [x] Search implementation
Health screen  #90
- [x] Expandable list tile
- [x] Custom list tiles, mostly reusable from other screens
- [x] Rebble account card (smaller version, different actions)
- [x] Modal bottom sheet with another ListView

**Comment by piggehperson** [comment]
Hey I've seen your work on widget theming in the Discord and it looks perfect, could we get the wording of this issue changed to clarify we're using Material components/styles with Cupertino navigation behavior? ty

**Comment by DreadBoy** [comment]
Oh yeah, I forgot to update it here once I figured out components are still going to be from Material library. Thanks for reminder.

**Comment by jwise** [comment]
I think you actually sold yourself a little short here -- you did a bunch of important architecture for testability, which wasn't captured in the checklist!  I'm reviewing it with ishotjr now and hope to get back to you shortly.

**Comment by DreadBoy** [comment]
UI is done. Apps on "Alerting apps" screen are mocked because native plugin is yet to be implemented to support this functionality. Work on this plugin is tracked in #94.

**Comment by jwise** [comment]
🎉 The Rebble Alliance is glad to fund this work at $1500 -- and, on top of that, I believe that it is complete as described! ❤️ cc: @ishotjr
