### ISSUE TITLE
Watches page is pretty buggy

### ISSUE THREAD

**Issue by matejdro** [pebble-dev/mobile-app#97]
- [ ] Pressing on "Pair a watch" button sometimes just returns user to "Testing" and creates another bottom bar

https://gfycat.com/dearblackitaliangreyhound

- [ ] Tapping on disconnected watch does nothing. I assume it should start connection process? I have to tap on the 3 dots on the right and press connect. EDIT: I'm an idiot. I should have pressed on connect icon.
- [ ] When watch is "Connecting", background services are running, so top part should not say background service stopped. Maybe connecting watch should even move to the top?

![image](https://user-images.githubusercontent.com/507922/109381771-900f6b80-78dc-11eb-8138-c4a941ac7f37.png)

- [ ] When watch is "Connecting", there is no way to stop this connection
- [ ] Forget Watch does nothing
- [ ] Pair screen:
  - [ ]  "Search again" does not immediately clear out previous watch list
  - [ ]  "Search again" buttons should probably be hidden when search is in progress? 
  - [ ]  Pressing back button exits the app instead of returning to the Watches page
  - [ ] When you tap on "Search again with BT Classic", text will move down due to the loading, but ripple effect will stay at the top, making it appear like user tapped BLE button, not BT Classic button

**Comment by piggehperson** [comment]
I actually would really like tapping a disconnected watch to connect to it! Someone failing to understand a design is a fault of the design, not the user, and it's been bothering me for a while that nothing happens when you tap

**Comment by AliceGrey** [comment]
> I actually would really like tapping a disconnected watch to connect to it! Someone failing to understand a design is a fault of the design, not the user, and it's been bothering me for a while that nothing happens when you tap

That seems like unexpected behavior. I don't think users who do understand the design will expect that. I think a better option would be to tell the user with a popup or toast notification "can't disconnect from watch since we aren't connected"or something along those lines.

**Comment by AliceGrey** [comment]
I think that this bug should probably be split into at least two bugs to make it more manageable. The pair page issues are unrelated to the watch page as it's a separate part of the app.

**Comment by DreadBoy** [comment]
> That seems like unexpected behavior. I don't think users who do understand the design will expect that. I think a better option would be to tell the user with a popup or toast notification "can't disconnect from watch since we aren't connected"or something along those lines.

Or we could have a single button that disconnects a watch when it's connected or connect it when it's disconnected. Icon would change depending on the action, of course. 

Also, I can try and fix these bugs if nobody is currently working on this.

**Comment by matejdro** [comment]
> I think that this bug should probably be split into at least two bugs to make it more manageable. The pair page issues are unrelated to the watch page as it's a separate part of the app.

Yeah I think you are right. Should I create separate issues for every bug or just leave it as a compilation?

**Comment by AliceGrey** [comment]
> > I think that this bug should probably be split into at least two bugs to make it more manageable. The pair page issues are unrelated to the watch page as it's a separate part of the app.
> 
> Yeah I think you are right. Should I create separate issues for every bug or just leave it as a compilation?

I think one issue per bug would be a good standard. Makes it easier for newcomers and makes bugs more specific and trackable.

**Comment by matejdro** [comment]
Good point, made separate tickets.

**Comment by matejdro** [comment]
@DreadBoy I think as long as nobody is assigned to a ticket, you are free to assign yourself and start working it. If someone already started is his fault for not assigning him/herself.
